server:
  port: 8080

zipcode:
  client:
    address:
      url: http://localhost:8082/addresses

spring: 
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=Wallet;encrypt=false
    username: sa
    password: 031491
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher

springdoc:
  api-docs:
    path: /v3/api-docs
 
